### ISSUE TITLE
Remove phone number from credentials.py and add test number

### ISSUE THREAD

**Issue by Sadnesh** [kali-37/MikroTik-Hotspot-auto-Login-Form#1]

**Comment by kali-37** [comment]
Great observation @Sadnesh ,
Though the credentials was random , it might belong to another random person :) . 
[changes](https://github.com/kali-37/MikroTik-Hotspot-auto-Login-Form/blob/b40784e8c6068983a40779c4ac7b09ad3064b757/credentials.py#L1)
